# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies with Make
      run: |
        python3 -m venv venv
        . venv/bin/activate
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
    - name: Run server with Make and sleep
      run: |
        . venv/bin/activate
        make run > server_log.txt 2>&1 &
        sleep 30
    - name: Print server log
      run: cat server_log.txt
    - name: Verify server is running
      run: |
        curl --fail http://localhost:3000 || exit 1
  

